@echo off
start chrome "http://localhost/posmev4/app_accounting_account/posMeGetRutasOfController" --incognito
start chrome "http://localhost/posmev4/app_accounting_api/posMeGetRutasOfController" --incognito
start chrome "http://localhost/posmev4/app_accounting_class/posMeGetRutasOfController" --incognito
start chrome "http://localhost/posmev4/app_accounting_currency/posMeGetRutasOfController" --incognito
start chrome "http://localhost/posmev4/app_accounting_dashboards/posMeGetRutasOfController" --incognito
start chrome "http://localhost/posmev4/app_accounting_journal/posMeGetRutasOfController" --incognito
start chrome "http://localhost/posmev4/app_accounting_level/posMeGetRutasOfController" --incognito
start chrome "http://localhost/posmev4/app_accounting_parameters/posMeGetRutasOfController" --incognito
start chrome "http://localhost/posmev4/app_accounting_period/posMeGetRutasOfController" --incognito
start chrome "http://localhost/posmev4/app_accounting_process/posMeGetRutasOfController" --incognito
start chrome "http://localhost/posmev4/app_accounting_report/posMeGetRutasOfController" --incognito
start chrome "http://localhost/posmev4/app_accounting_type/posMeGetRutasOfController" --incognito
start chrome "http://localhost/posmev4/app_afx_fixedassent/posMeGetRutasOfController" --incognito
start chrome "http://localhost/posmev4/app_box_api/posMeGetRutasOfController" --incognito
start chrome "http://localhost/posmev4/app_box_canceldocument/posMeGetRutasOfController" --incognito
start chrome "http://localhost/posmev4/app_box_inputcash/posMeGetRutasOfController" --incognito
start chrome "http://localhost/posmev4/app_box_outcash/posMeGetRutasOfController" --incognito
start chrome "http://localhost/posmev4/app_box_provisioned/posMeGetRutasOfController" --incognito
start chrome "http://localhost/posmev4/app_box_report/posMeGetRutasOfController" --incognito
start chrome "http://localhost/posmev4/app_box_share/posMeGetRutasOfController" --incognito
start chrome "http://localhost/posmev4/app_box_sharecapital/posMeGetRutasOfController" --incognito
start chrome "http://localhost/posmev4/app_catalog_api/posMeGetRutasOfController" --incognito
start chrome "http://localhost/posmev4/app_collection_manager/posMeGetRutasOfController" --incognito
start chrome "http://localhost/posmev4/app_collection_report/posMeGetRutasOfController" --incognito
start chrome "http://localhost/posmev4/app_config_noti/posMeGetRutasOfController" --incognito
start chrome "http://localhost/posmev4/app_cxc_api/posMeGetRutasOfController" --incognito
start chrome "http://localhost/posmev4/app_cxc_creditline/posMeGetRutasOfController" --incognito
start chrome "http://localhost/posmev4/app_cxc_customer/posMeGetRutasOfController" --incognito
start chrome "http://localhost/posmev4/app_cxc_process/posMeGetRutasOfController" --incognito
start chrome "http://localhost/posmev4/app_cxc_record/posMeGetRutasOfController" --incognito
start chrome "http://localhost/posmev4/app_cxc_report/posMeGetRutasOfController" --incognito
start chrome "http://localhost/posmev4/app_cxc_simulation/posMeGetRutasOfController" --incognito
start chrome "http://localhost/posmev4/app_cxp_provider/posMeGetRutasOfController" --incognito
start chrome "http://localhost/posmev4/app_inventory_api/posMeGetRutasOfController" --incognito
start chrome "http://localhost/posmev4/app_inventory_category/posMeGetRutasOfController" --incognito
start chrome "http://localhost/posmev4/app_inventory_dashboards/posMeGetRutasOfController" --incognito
start chrome "http://localhost/posmev4/app_inventory_datasheet/posMeGetRutasOfController" --incognito
start chrome "http://localhost/posmev4/app_inventory_inputunpost/posMeGetRutasOfController" --incognito
start chrome "http://localhost/posmev4/app_inventory_item/posMeGetRutasOfController" --incognito
start chrome "http://localhost/posmev4/app_inventory_itemmasive/posMeGetRutasOfController" --incognito
start chrome "http://localhost/posmev4/app_inventory_otherinput/posMeGetRutasOfController" --incognito
start chrome "http://localhost/posmev4/app_inventory_otheroutput/posMeGetRutasOfController" --incognito
start chrome "http://localhost/posmev4/app_inventory_process/posMeGetRutasOfController" --incognito
start chrome "http://localhost/posmev4/app_inventory_report/posMeGetRutasOfController" --incognito
start chrome "http://localhost/posmev4/app_inventory_requestgeneral/posMeGetRutasOfController" --incognito
start chrome "http://localhost/posmev4/app_inventory_transferinput/posMeGetRutasOfController" --incognito
start chrome "http://localhost/posmev4/app_inventory_transferoutput/posMeGetRutasOfController" --incognito
start chrome "http://localhost/posmev4/app_inventory_warehouse/posMeGetRutasOfController" --incognito
start chrome "http://localhost/posmev4/app_invoice_api/posMeGetRutasOfController" --incognito
start chrome "http://localhost/posmev4/app_invoice_billing/posMeGetRutasOfController" --incognito
start chrome "http://localhost/posmev4/app_invoice_dashboards/posMeGetRutasOfController" --incognito
start chrome "http://localhost/posmev4/app_invoice_price/posMeGetRutasOfController" --incognito
start chrome "http://localhost/posmev4/app_notification/posMeGetRutasOfController" --incognito
start chrome "http://localhost/posmev4/app_planilla_adelantos/posMeGetRutasOfController" --incognito
start chrome "http://localhost/posmev4/app_planilla_employee_pay/posMeGetRutasOfController" --incognito
start chrome "http://localhost/posmev4/app_purchase_api/posMeGetRutasOfController" --incognito
start chrome "http://localhost/posmev4/app_purchase_dashboards/posMeGetRutasOfController" --incognito
start chrome "http://localhost/posmev4/app_purchase_internalpurchaserequest/posMeGetRutasOfController" --incognito
start chrome "http://localhost/posmev4/app_purchase_purchaseorden/posMeGetRutasOfController" --incognito
start chrome "http://localhost/posmev4/app_purchase_returnsprovider/posMeGetRutasOfController" --incognito
start chrome "http://localhost/posmev4/app_rrhh_employee/posMeGetRutasOfController" --incognito
start chrome "http://localhost/posmev4/app_sales_report/posMeGetRutasOfController" --incognito
start chrome "http://localhost/posmev4/app_transaction_config/posMeGetRutasOfController" --incognito
start chrome "http://localhost/posmev4/core_acount/posMeGetRutasOfController" --incognito
start chrome "http://localhost/posmev4/core_concept_api/posMeGetRutasOfController" --incognito
start chrome "http://localhost/posmev4/core_dashboards/posMeGetRutasOfController" --incognito
start chrome "http://localhost/posmev4/core_elfinder/posMeGetRutasOfController" --incognito
start chrome "http://localhost/posmev4/core_notification/posMeGetRutasOfController" --incognito
start chrome "http://localhost/posmev4/core_role/posMeGetRutasOfController" --incognito
start chrome "http://localhost/posmev4/core_testunitary/posMeGetRutasOfController" --incognito
start chrome "http://localhost/posmev4/core_user/posMeGetRutasOfController" --incognito
start chrome "http://localhost/posmev4/core_view/posMeGetRutasOfController" --incognito
